{% set name = "ratarmountcore" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ratarmountcore-{{ version }}.tar.gz
  sha256: 564393eae729a6fba0ed6964dc5a47d1a4aeabedd3b486a6453bb859a4f9c499

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - dataclasses
    - importlib-metadata

test:
  imports:
    - ratarmountcore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/mxmlnkn/ratarmount/tree/master/core
  summary: Random Access Read-Only Tar Mount Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ap--
    - mxmlnkn
